version: '3'

vars:
  PLANETILER_DOCKERFILE: Dockerfile.planetiler
  PLANETILER_IMAGE: planetiler:latest
  PMTILES_DIR: ./tiles

tasks:
  build-tiles:
    desc: Build vector tiles using Planetiler
    cmds:
      - docker build -f {{.PLANETILER_DOCKERFILE}} -t {{.PLANETILER_IMAGE}} .
      - docker run --rm -v {{.PMTILES_DIR}}:/data {{.PLANETILER_IMAGE}}
    silent: true
